In [4]:
import numpy as np
import random
from time import sleep

def create():
  return np.array([[0,0,0],
                  [0,0,0],
                  [0,0,0]])
  
def possibilities(board):
  l=[]
  for i in range(len(board)):
    for j in range(len(board)):
      if board[i,j]==0:
        l.append((i,j))
  return l

def random11(board,player):
  sel=possibilities(board)
  pos=random.choice(sel)
  #print(pos)
  if player==1:
    i=int(input("Enter row:"))
    j=int(input("Enter col:"))
    board[(i,j)]=player
  else:
    board[pos]=player

  return board

def check_hori(board,player):
  for i in range(len(board)):
    win=True
    for j in range(len(board)):
      if board[i,j]!=player:
        win=False
        continue

    if win:
      return win
  return win

def check_vertical(board,player):
  for i in range(len(board)):
    win =True
    for j in range(len(board)):
      if board[j,i]!=player:
        win=False
        continue

    if win:
      return win
  return win

def check_diagonal(board,player):
  win=True
  for i in range(len(board)):
    if board[i,i]!=player:
      win=False
      continue
  if win==True:
    return win

  win =True
  for i in range(len(board)):
    j=len(board)-i-1
    if board[i,j]!=player:
      win=False
      continue
  return win

  
def evaluates(board):
  winner=0
  for player in [1,2]:
    if(check_hori(board,player) or check_vertical(board,player) or check_diagonal(board,player)):
      winner=player
  return winner

  if winner==0 and np.all(board!=0):
    winner=-1
  return winner

def start_game():
  the_board=create()
  winner=0
  count=1
  print(the_board)
  sleep(2)

  while winner==0:
    for player in [1,2]:
      the_board=random11(the_board,player)
      print("The Board after "+ str(count) +" moves")
      print(the_board)
      sleep(2)
      count+=1
      winner=evaluates(the_board)
      if(winner!=0):
        break
  return winner

print("Winner is"+ str(start_game()))
print("game over")  

    

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Enter row:1
Enter col:1
The Board after 1 moves
[[0 0 0]
 [0 1 0]
 [0 0 0]]
The Board after 2 moves
[[0 0 0]
 [2 1 0]
 [0 0 0]]
Enter row:000
Enter col:0
The Board after 3 moves
[[1 0 0]
 [2 1 0]
 [0 0 0]]
The Board after 4 moves
[[1 0 0]
 [2 1 0]
 [2 0 0]]
Enter row:2
Enter col:2
The Board after 5 moves
[[1 0 0]
 [2 1 0]
 [2 0 1]]
Winner is1
game over
